### PR TITLE
Use collapsable groups on CI

### LINKED ISSUE #105: Use collapsable groups on CI
Image

Let's make everything after the FAILED header a collapsible group when running on CI. See https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions?#grouping-log-lines and https://pkg.go.dev/github.com/sethvargo/go-githubactions#Group

### PR DESCRIPTION
**Pull request by noisersup**
Closes #105.

### CODE REVIEW

**Review by chilagrow — DISMISSED** [review]

File: opendocdb-cts/main.go [hunk 1]
```diff
@@ -140,7 +140,7 @@ func runCommand(ctx context.Context, l *slog.Logger) error {
 			l.InfoContext(ctx, name+": PASSED")
 			results = append(results, testresult.TestSuiteResult{Name: name, Passed: true})
 		} else {
-			l.ErrorContext(ctx, name+": FAILED\n"+err.Error())
+			l.ErrorContext(ctx, name+": FAILED\n::group::Error\n"+err.Error()+"\n::endgroup::")
```
Comment (AlekSi) [inline opendocdb-cts/main.go:143]: Well, that makes the local output worse.

The issue specifically points out https://pkg.go.dev/github.com/sethvargo/go-githubactions#Group. I think this library does nothing if it is not running on GitHub Actions.

Comment (noisersup) [reply opendocdb-cts/main.go:148]: I'm not sure if the usage of the library gives any profits at this point.
Those helper functions just print `group` and `endgroup` into the underlying writer, which by default is just set to `os.Stdout`.
It doesn't perform any checks if we're running on CI or not.

I've added check for `GITHUB_ACTIONS` env variable. Please let me know if we want to use the library in those circumstances.

**Review by AlekSi — APPROVED** [review]
